// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxGV8Q5g4Quf3InA5cPtWxXncULzFgaQo',
    appId: '1:561689287957:web:972e9e1ef6112cf3bfdd1c',
    messagingSenderId: '561689287957',
    projectId: 'pet-care-app-4009d',
    authDomain: 'pet-care-app-4009d.firebaseapp.com',
    storageBucket: 'pet-care-app-4009d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF_2S5axmhTw5ANTOqTBp7kodoKGqBry4',
    appId: '1:561689287957:android:99836a8f9c2e80bbbfdd1c',
    messagingSenderId: '561689287957',
    projectId: 'pet-care-app-4009d',
    storageBucket: 'pet-care-app-4009d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcEp4dSn1DUKLhrNyHOY2E4mXHYXKAyIk',
    appId: '1:561689287957:ios:63c9529b91888502bfdd1c',
    messagingSenderId: '561689287957',
    projectId: 'pet-care-app-4009d',
    storageBucket: 'pet-care-app-4009d.firebasestorage.app',
    iosBundleId: 'com.example.petCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcEp4dSn1DUKLhrNyHOY2E4mXHYXKAyIk',
    appId: '1:561689287957:ios:63c9529b91888502bfdd1c',
    messagingSenderId: '561689287957',
    projectId: 'pet-care-app-4009d',
    storageBucket: 'pet-care-app-4009d.firebasestorage.app',
    iosBundleId: 'com.example.petCareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxGV8Q5g4Quf3InA5cPtWxXncULzFgaQo',
    appId: '1:561689287957:web:f93d46c070bdcb02bfdd1c',
    messagingSenderId: '561689287957',
    projectId: 'pet-care-app-4009d',
    authDomain: 'pet-care-app-4009d.firebaseapp.com',
    storageBucket: 'pet-care-app-4009d.firebasestorage.app',
  );
}
